export interface IImageProduct {
  id: number;
  imageUrl: string;
  itemId: number;
}
export interface IProduct {
  id: number;
  nameAr: string;
  nameEng: string;
  nameAbree: string;
  NameAr?: string;
  NameEng?: string;
  NameAbree?: string;
  supCategoryId: string;
  isShow: boolean;
  model: string;
  Model?: string;
  isNewItem: boolean;
  isMoreSales: boolean;
  rate: number;
  manufactureYear: number;
  ManufactureYear?: number;
  descriptionAr: string;
  DescriptionAr?: string;
  descriptionEng: string;
  DescriptionEng?: string;
  descriptionAbree: string;
  DescriptionAbree?: string;
  videoUrl: string | null;
  Video?: File | null;
  normailPrice: number;
  NormailPrice?: number;
  wholesalePrice: number;
  WholesalePrice?: number;
  stock: number;
  Stock?: number;
  discount: number;
  Discount?: number;
  userIdAdd: string;
  dateAdd: string;
  userIdUpdate: string;
  dateUpdate: string | Date;
  DateUpdate?: string | Date;
  supCategory: null;
  SupCategoryId?: string | number;
  normalImagesItems: IImageProduct[];
  NormalImg?: File[] | [];
  _3DImagesItems: IImageProduct[];
  threeDImg?: File[] | [];
  viewImagesItems: IImageProduct[];
  ViewImg?: File[] | [];
}
